spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    password: Thewipper.
    url: jdbc:postgresql://localhost:8080/fitnes
    username: postgres