spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    password: postgres
    url: jdbc:postgresql://postgresqldb:5432/fitnesso
    username: postgres
  mvc:
  pathmatch:
  matching-strategy: ANT_PATH_MATCHER